version: '3.8'

services:
  telegram-bot:
    build:
      context: .  # Path to your Dockerfile
      dockerfile: Dockerfile
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    volumes:
      - .:/app
